'use server';

/**
 * @fileOverview Simulates bargaining with an AI buddy to generate negotiation text and confidence scores.
 *
 * - simulateBargaining - A function that simulates bargaining and returns negotiation suggestions.
 * - SimulateBargainingInput - The input type for the simulateBargaining function.
 * - SimulateBargainingOutput - The return type for the simulateBargaining function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SimulateBargainingInputSchema = z.object({
  productDescription: z
    .string()
    .describe('The description of the product for which to simulate bargaining.'),
  userBudget: z.number().describe('The user budget for the product.'),
  userPreferences: z
    .string()
    .describe('The user preferences related to the product.'),
});
export type SimulateBargainingInput = z.infer<typeof SimulateBargainingInputSchema>;

const SimulateBargainingOutputSchema = z.object({
  negotiationSuggestions: z
    .array(z.string())
    .describe('An array of negotiation suggestions generated by the AI.'),
  confidenceScores: z
    .array(z.number())
    .describe('An array of confidence scores for each negotiation suggestion.'),
});
export type SimulateBargainingOutput = z.infer<typeof SimulateBargainingOutputSchema>;

export async function simulateBargaining(input: SimulateBargainingInput): Promise<SimulateBargainingOutput> {
  return simulateBargainingFlow(input);
}

const simulateBargainingPrompt = ai.definePrompt({
  name: 'simulateBargainingPrompt',
  input: {schema: SimulateBargainingInputSchema},
  output: {schema: SimulateBargainingOutputSchema},
  prompt: `You are an AI Bargain Buddy, an expert in simulating negotiations for products.

You will receive a product description, the user's budget, and the user's preferences.
Based on this information, generate negotiation suggestions and compute confidence scores for each suggestion.

Product Description: {{{productDescription}}}
User Budget: {{{userBudget}}}
User Preferences: {{{userPreferences}}}

Negotiation Suggestions and Confidence Scores:
`,
});

const simulateBargainingFlow = ai.defineFlow(
  {
    name: 'simulateBargainingFlow',
    inputSchema: SimulateBargainingInputSchema,
    outputSchema: SimulateBargainingOutputSchema,
  },
  async input => {
    const {output} = await simulateBargainingPrompt(input);
    return output!;
  }
);
