import { type Product } from './types';

export const products: Product[] = [
  // ── Laptops ──────────────────────────────────────────────────────────────
  {
    id: "prod_laptop_1",
    name: "Apple MacBook Pro 16 M3 Max",
    category: "Laptops",
    price: 249900,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80&auto=format&fit=crop",
    imageHint: "macbook laptop apple",
    description: "The most powerful MacBook Pro ever. Featuring the M3 Max chip with a 16-core CPU and 40-core GPU, 48 GB unified memory, and a stunning 16-inch Liquid Retina XDR display. Built for professionals who demand maximum performance in creative and scientific workloads.",
    specifications: "M3 Max Chip, 16-core CPU, 40-core GPU, 48GB Unified Memory, 1TB SSD, 16\" Liquid Retina XDR (3456x2234), Thunderbolt 4, 22-hr battery",
  },
  {
    id: "prod_laptop_2",
    name: "Dell XPS 15 (2024)",
    category: "Laptops",
    price: 159990,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd81f4a181?w=800&q=80&auto=format&fit=crop",
    imageHint: "dell xps laptop",
    description: "Dell's premium workhorse featuring a stunning 15.6-inch OLED display with 100% DCI-P3 colour coverage. Powered by Intel Core Ultra 9 and NVIDIA RTX 4070, it is equally at home for creative work and demanding enterprise tasks.",
    specifications: "Intel Core Ultra 9-185H, NVIDIA RTX 4070 8GB, 32GB DDR5, 1TB NVMe SSD, 15.6\" 3.5K OLED 60Hz, Thunderbolt 5, 86Wh battery",
  },
  {
    id: "prod_laptop_3",
    name: "ASUS ROG Zephyrus G16 (2024)",
    category: "Laptops",
    price: 189990,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80&auto=format&fit=crop",
    imageHint: "gaming laptop asus rog",
    description: "A gaming powerhouse disguised in an ultra-thin chassis. The Zephyrus G16 pairs AMD Ryzen 9 with NVIDIA RTX 4090 for uncompromising 1440p gameplay. The 2560x1600 ROG Nebula Display at 240 Hz delivers buttery-smooth visuals with factory-calibrated colour accuracy.",
    specifications: "AMD Ryzen 9 8945HS, NVIDIA RTX 4090 16GB, 32GB DDR5, 2TB NVMe SSD, 16\" QHD+ 240Hz ROG Nebula Display, MUX Switch, Tri-fan cooling",
  },
  {
    id: "prod_laptop_4",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    category: "Laptops",
    price: 139990,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80&auto=format&fit=crop",
    imageHint: "thinkpad lenovo business laptop",
    description: "The gold standard for business laptops. Weighing just 1.12 kg, the X1 Carbon Gen 12 is MIL-STD-810H certified for reliability. Its Intel Core Ultra processor, 14-inch IPS display, and legendary ThinkPad keyboard make it the ultimate road-warrior companion.",
    specifications: "Intel Core Ultra 7-165U, Intel Arc Graphics, 32GB LPDDR5x, 1TB SSD, 14\" IPS 2.8K OLED, MIL-STD-810H, 57.4Wh battery, 1.12 kg",
  },
  {
    id: "prod_laptop_5",
    name: "HP Spectre x360 14 OLED",
    category: "Laptops",
    price: 179900,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80&auto=format&fit=crop",
    imageHint: "hp spectre convertible laptop",
    description: "The Spectre x360 is HP's most premium 2-in-1, featuring a jewel-cut design in Nightfall Black. Its 14-inch 2.8K OLED touchscreen rotates 360 degrees for laptop, tent, and tablet modes. Powered by Intel Core Ultra with integrated Arc graphics for everyday brilliance.",
    specifications: "Intel Core Ultra 7-155H, Intel Arc Graphics, 32GB LPDDR5, 2TB SSD, 14\" 2.8K OLED Touch 120Hz, 360-degree hinge, Wi-Fi 7, HP Tilt Pen included",
  },

  // ── Smartphones ──────────────────────────────────────────────────────────
  {
    id: "prod_smartphone_1",
    name: "Samsung Galaxy S24 Ultra",
    category: "Smartphones",
    price: 134999,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80&auto=format&fit=crop",
    imageHint: "samsung galaxy s24 ultra smartphone",
    description: "Samsung's flagship redefines what a smartphone can do. The titanium-framed S24 Ultra integrates a built-in S Pen stylus, a 200MP quad-camera system with 100x Space Zoom, and Galaxy AI for real-time translation and circle-to-search. A true productivity powerhouse.",
    specifications: "Snapdragon 8 Gen 3, 12GB RAM, 256GB storage, 200MP + 50MP + 12MP + 10MP cameras, 6.8\" QHD+ Dynamic AMOLED 2X 120Hz, 5000mAh, 45W wired charging, S Pen",
  },
  {
    id: "prod_smartphone_2",
    name: "Apple iPhone 15 Pro Max",
    category: "Smartphones",
    price: 159900,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=800&q=80&auto=format&fit=crop",
    imageHint: "iphone 15 pro max apple smartphone",
    description: "Crafted from aerospace-grade titanium, the iPhone 15 Pro Max is the most capable iPhone ever made. The A17 Pro chip enables hardware-accelerated ray tracing for console-quality gaming. Its 48MP main camera with 5x optical zoom and Action Button make it an unmatched creative tool.",
    specifications: "A17 Pro, 8GB RAM, 256GB, 48MP + 12MP + 12MP camera system, 5x optical zoom, 6.7\" Super Retina XDR ProMotion 120Hz, Titanium frame, USB-C 3.0",
  },
  {
    id: "prod_smartphone_3",
    name: "Google Pixel 8 Pro",
    category: "Smartphones",
    price: 106999,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80&auto=format&fit=crop",
    imageHint: "google pixel 8 pro android smartphone",
    description: "Pure Android perfection with Google's most advanced AI features. Tensor G3 chip powers Magic Eraser, Best Take, and Audio Magic Eraser. The 50MP camera with a temperature sensor and 7 years of guaranteed Android updates make it the most future-proof Android phone available.",
    specifications: "Google Tensor G3, 12GB RAM, 128GB, 50MP + 48MP + 48MP cameras, 6.7\" LTPO OLED 120Hz, 5050mAh, 30W wired charging, Temperature sensor",
  },
  {
    id: "prod_smartphone_4",
    name: "OnePlus 12",
    category: "Smartphones",
    price: 64999,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80&auto=format&fit=crop",
    imageHint: "oneplus 12 flagship android phone",
    description: "Flagship speed at a flagship-competitive price. The OnePlus 12 sports Hasselblad-tuned cameras, a breathtaking 2K ProXDR display, and 100W SuperVOOC charging that fully charges its 5400 mAh battery in under 30 minutes. Never wait for power again.",
    specifications: "Snapdragon 8 Gen 3, 16GB RAM, 512GB, 50MP Hasselblad + 48MP + 64MP cameras, 6.82\" 2K LTPO3 AMOLED 120Hz, 5400mAh, 100W SuperVOOC charging",
  },
  {
    id: "prod_smartphone_5",
    name: "Nothing Phone (2a)",
    category: "Smartphones",
    price: 23999,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80&auto=format&fit=crop",
    imageHint: "nothing phone 2a transparent back design",
    description: "The most exciting mid-ranger in years. Nothing Phone (2a) features the iconic transparent back with Glyph Interface LEDs that light up with notifications and calls. A 50MP dual camera, 5000 mAh battery with 45W charging, and near-stock Android make it exceptional value.",
    specifications: "MediaTek Dimensity 7200 Pro, 8GB RAM, 128GB, 50MP + 50MP cameras, 6.7\" AMOLED 120Hz, 5000mAh, 45W fast charging, Glyph Interface, Transparent design",
  },

  // ── Headphones ───────────────────────────────────────────────────────────
  {
    id: "prod_headphones_1",
    name: "Sony WH-1000XM5",
    category: "Headphones",
    price: 29990,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80&auto=format&fit=crop",
    imageHint: "sony wh1000xm5 wireless noise cancelling headphones",
    description: "Sony's best-in-class noise cancelling headphones. Eight microphones and two processors work together to block out the world, while 30 hours of playtime keeps the music going. The new soft-fit leather earcups and foldable design make them perfect for long-haul flights.",
    specifications: "8 mics + 2 processors ANC, 30-hr battery, LDAC Hi-Res Wireless, Multipoint (2 devices), Speak-to-Chat, 360 Reality Audio, 30-min quick charge = 3 hrs",
  },
  {
    id: "prod_headphones_2",
    name: "Bose QuietComfort Ultra",
    category: "Headphones",
    price: 34900,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80&auto=format&fit=crop",
    imageHint: "bose quietcomfort over ear headphones",
    description: "Bose's finest headphones ever. World-class noise cancellation is combined with Bose Immersive Audio — a spatial sound mode that places music all around you. CustomTune automatically adjusts EQ and ANC to the unique shape of your ears the moment you put them on.",
    specifications: "CustomTune ANC, 24-hr battery with ANC on, Immersive Audio spatial sound, LDAC, Multipoint, USB-C + 3.5mm, Wind Noise Reduction mode",
  },
  {
    id: "prod_headphones_3",
    name: "Apple AirPods Max",
    category: "Headphones",
    price: 59900,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=800&q=80&auto=format&fit=crop",
    imageHint: "apple airpods max over ear headphones",
    description: "Apple's over-ear masterpiece with an anodised aluminium ear cup, stainless steel headband, and knit mesh canopy. Spatial Audio with dynamic head tracking makes movies and music feel three-dimensional. Perfect for Apple ecosystem users who want the ultimate listening experience.",
    specifications: "Apple H1 chip per cup, Computational ANC, Transparency mode, Spatial Audio, 20-hr battery, Smart Case included",
  },
  {
    id: "prod_headphones_4",
    name: "Sennheiser Momentum 4 Wireless",
    category: "Headphones",
    price: 26990,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80&auto=format&fit=crop",
    imageHint: "sennheiser momentum 4 over ear headphones",
    description: "Sennheiser's most refined wireless headphones offer a staggering 60 hours of playtime — the longest of any premium ANC headphone. Adaptive Noise Cancellation automatically adjusts to your environment, while the Sound app lets you tailor EQ to your taste.",
    specifications: "Adaptive ANC, 60-hr battery, LDAC, AAC, Customisable EQ via app, Touch controls, USB-C charging, Foldable, 233g",
  },
  {
    id: "prod_headphones_5",
    name: "Anker Soundcore Space Q45",
    category: "Headphones",
    price: 7999,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80&auto=format&fit=crop",
    imageHint: "anker soundcore wireless headphones budget",
    description: "The most capable budget ANC headphones on the market. Upgraded noise cancellation blocks up to 98% of ambient sound, while Hi-Res Wireless Audio via LDAC delivers studio-quality sound. At under Rs 8000, it punches way above its weight class.",
    specifications: "Upgraded ANC (98% noise reduction), 50-hr battery, LDAC Hi-Res, Ambient Sound mode, Multipoint, USB-C, 3.5mm, App with EQ customisation",
  },

  // ── Smartwatches ─────────────────────────────────────────────────────────
  {
    id: "prod_smartwatch_1",
    name: "Apple Watch Ultra 2",
    category: "Smartwatches",
    price: 89900,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80&auto=format&fit=crop",
    imageHint: "apple watch ultra titanium smartwatch",
    description: "Built for extreme athletes and adventurers. The Apple Watch Ultra 2 features a 49mm titanium case, the brightest Apple Watch display at 3000 nits, 60-hour battery in Low Power Mode, and water resistance to 100m. The dual-frequency GPS is accurate enough for professional trail navigation.",
    specifications: "S9 SiP, 49mm Titanium, 3000 nits, 36-hr / 60-hr Low Power Mode, 100m water resistance, Dual-frequency GPS, Action button, Cellular, watchOS 10",
  },
  {
    id: "prod_smartwatch_2",
    name: "Samsung Galaxy Watch 6 Classic 47mm",
    category: "Smartwatches",
    price: 37990,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80&auto=format&fit=crop",
    imageHint: "samsung galaxy watch classic rotating bezel",
    description: "The rotating bezel returns in the Galaxy Watch 6 Classic — the most tactile and satisfying smartwatch interaction on Android. Sapphire crystal glass, a 47mm stainless steel case, and advanced health sensors including ECG, blood pressure, and body composition complete the package.",
    specifications: "Exynos W930, 47mm Stainless Steel, Sapphire Crystal, Rotating Bezel, ECG + Blood Pressure, Body Composition, Wear OS 4, 425mAh battery, 5ATM + IP68",
  },
  {
    id: "prod_smartwatch_3",
    name: "Garmin Fenix 7X Pro Solar",
    category: "Smartwatches",
    price: 94990,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80&auto=format&fit=crop",
    imageHint: "garmin fenix pro solar gps sports watch",
    description: "The ultimate GPS multisport watch for serious athletes. Solar charging extends battery life up to 37 days in smartwatch mode. Built-in maps with turn-by-turn navigation, a flashlight, and advanced training metrics like VO2 Max make it the definitive performance tracker.",
    specifications: "51mm DLC Titanium, Solar Charging, 37-day battery (solar), Multi-band GPS, Pulse Ox, HRV Status, Built-in topographic maps, Flashlight, 10 ATM, Garmin Pay",
  },
  {
    id: "prod_smartwatch_4",
    name: "Google Pixel Watch 2",
    category: "Smartwatches",
    price: 29999,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80&auto=format&fit=crop",
    imageHint: "google pixel watch 2 round smartwatch",
    description: "Google and Fitbit combine their expertise in the Pixel Watch 2. The new cEDA sensor tracks stress responses throughout the day, while Safety Check and Emergency SOS keep you protected. Deep Google services integration and a lightweight recycled aluminium case make it compelling.",
    specifications: "Qualcomm SW5100, 41mm Recycled Aluminium, cEDA stress sensor, ECG, Continuous HR, Skin temperature, 24-hr battery, Fast charging 80% in 47 min, Wear OS 4, Cellular",
  },
  {
    id: "prod_smartwatch_5",
    name: "Fitbit Sense 2",
    category: "Smartwatches",
    price: 20999,
    rating: 4.2,
    imageUrl: "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&q=80&auto=format&fit=crop",
    imageHint: "fitbit sense 2 health smartwatch",
    description: "Your personal health assistant on your wrist. The Fitbit Sense 2 tracks stress with a continuous EDA sensor, monitors your heart health with ECG and irregular rhythm notifications, and gives you a Daily Readiness Score to guide your workouts. Six-plus days battery means you rarely need to charge.",
    specifications: "cEDA continuous stress, ECG, Skin temperature sensor, Blood oxygen SpO2, Built-in GPS, 6+ day battery, 40+ exercise modes, Google Assistant and Alexa",
  },

  // ── Mobile Phone Accessories ──────────────────────────────────────────────
  {
    id: "prod_powerbank_1",
    name: "Anker 737 Power Bank 24000 mAh",
    category: "Mobile Phone Accessories",
    price: 7999,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&q=80&auto=format&fit=crop",
    imageHint: "anker power bank portable charger",
    description: "The powerhouse of portable chargers. With 140W output from its USB-C port and a 24000 mAh capacity, the Anker 737 can charge a MacBook Pro to 50% in 30 minutes while simultaneously powering your phone and tablet. The built-in display shows wattage and remaining capacity in real time.",
    specifications: "24000mAh, 140W USB-C PD output, 65W USB-C input, 18W USB-A output, LCD display showing watt/capacity, Charges 3 devices at once, 624g",
  },
  {
    id: "prod_phonecase_1",
    name: "Spigen Ultra Hybrid iPhone 15 Pro Max Case",
    category: "Mobile Phone Accessories",
    price: 1499,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=800&q=80&auto=format&fit=crop",
    imageHint: "spigen clear iphone protective case",
    description: "The best-selling clear case for iPhone 15 Pro Max. Spigen Air Cushion Technology absorbs shocks at the corners, the most vulnerable points of impact. The crystal-clear back shows off your iPhone titanium finish while military-grade drop protection keeps it safe.",
    specifications: "Military-grade drop tested MIL-STD-810G, Air Cushion corners, Crystal-clear polycarbonate back, TPU bumper, Raised bezels, Wireless charging compatible",
  },
  {
    id: "prod_earbuds_1",
    name: "Apple AirPods Pro (2nd Gen)",
    category: "Mobile Phone Accessories",
    price: 24900,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800&q=80&auto=format&fit=crop",
    imageHint: "apple airpods pro 2nd gen earbuds case",
    description: "The world's best-selling true wireless earbuds. AirPods Pro 2 deliver up to 2x better Active Noise Cancellation than the previous generation. Adaptive Transparency muffles loud sounds while letting in the world around you. The H2 chip enables Personalized Spatial Audio for a concert-like experience.",
    specifications: "H2 chip, 2x ANC vs gen 1, Adaptive Transparency, Personalized Spatial Audio, 6hr ANC + 24hr with case MagSafe, IP68 sweat/water resistant, USB-C audio",
  },
  {
    id: "prod_charger_1",
    name: "Belkin BoostCharge Pro 3-in-1 MagSafe",
    category: "Mobile Phone Accessories",
    price: 8999,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80&auto=format&fit=crop",
    imageHint: "magsafe wireless charger pad multi device",
    description: "Charge your entire Apple ecosystem simultaneously on one sleek pad. The 15W MagSafe puck charges iPhone at maximum speed, while dedicated Apple Watch and AirPods pads complete your overnight charging ritual. No more juggling multiple cables on your bedside table.",
    specifications: "15W MagSafe for iPhone 12+, Apple Watch Fast Charge, AirPods wireless charging, Foldable design, USB-C power adapter included",
  },
  {
    id: "prod_carmount_1",
    name: "iOttie Easy One Touch Pro Dashboard Mount",
    category: "Mobile Phone Accessories",
    price: 3499,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80&auto=format&fit=crop",
    imageHint: "car phone dashboard mount holder",
    description: "Mount and unmount your phone with one hand while keeping your eyes on the road. The telescoping arm and 360-degree rotation let you position your phone exactly where you need it. Compatible with all phones from 5.7cm to 9.5cm wide, with or without a case.",
    specifications: "One-touch release mechanism, Telescoping arm adjustable length, 360-degree ball rotation, Dashboard + windshield mounting, Compatible with phones 57mm to 95mm wide",
  },

  // ── Cameras ───────────────────────────────────────────────────────────────
  {
    id: "prod_camera_1",
    name: "Sony Alpha A7 IV",
    category: "Cameras",
    price: 254990,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80&auto=format&fit=crop",
    imageHint: "sony alpha mirrorless camera full frame",
    description: "Sony's most versatile full-frame mirrorless camera, equally capable for photography and videography. The 33MP Exmor R BSI sensor produces stunning images from landscapes to portraits, while 4K 60p video with 10-bit 4:2:2 colour makes it a serious filmmaking tool.",
    specifications: "33MP Full-Frame Exmor R BSI CMOS, ISO 50 to 204800, 4K 60p / 1080p 120p, Real-time Eye AF, 759 phase-detect AF points, 5-axis IBIS, Dual SD slots",
  },
  {
    id: "prod_camera_2",
    name: "Canon EOS R6 Mark II",
    category: "Cameras",
    price: 234990,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=800&q=80&auto=format&fit=crop",
    imageHint: "canon eos mirrorless camera dslr",
    description: "Canon's flagship full-frame hybrid. The R6 II combines a 24.2MP sensor with blazing-fast 40fps continuous shooting and Canon's legendary Dual Pixel AF II, which tracks subjects across the entire frame with AI precision. A joy for sports, wildlife, and wedding photographers.",
    specifications: "24.2MP Full-Frame CMOS, 40fps electronic, 4K 60p 10-bit C-Log 3, Dual Pixel CMOS AF II, 5-axis IBIS up to 8 stops, Dual card slots CFexpress + SD",
  },
  {
    id: "prod_camera_3",
    name: "Fujifilm X-T5",
    category: "Cameras",
    price: 169999,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&q=80&auto=format&fit=crop",
    imageHint: "fujifilm xt5 retro design mirrorless",
    description: "The highest-resolution APS-C camera ever made with 40.2MP and Fujifilm's beloved Film Simulations. The X-T5 brings back the compact, traditional design with tactile dials for ISO, shutter speed, and exposure compensation. Its colour science is legendary among portrait and street photographers.",
    specifications: "40.2MP APS-C X-Trans CMOS 5 HR BSI, 7-stop IBIS, 6.2K 30p video, 20fps continuous, 425-point AF, Film Simulations Velvia Classic Chrome Eterna, 792g",
  },
  {
    id: "prod_camera_4",
    name: "GoPro HERO12 Black",
    category: "Cameras",
    price: 39990,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=800&q=80&auto=format&fit=crop",
    imageHint: "gopro hero action camera waterproof",
    description: "The most capable GoPro ever. HyperSmooth 6.0 delivers incredibly smooth footage even in extreme conditions, while the new 8:7 aspect ratio captures more sky and ground for flexible cropping. Built for adventure: waterproof to 10m, shockproof, and dustproof right out of the box.",
    specifications: "5.3K 60fps / 4K 120fps / 2.7K 240fps, HyperSmooth 6.0, 8:7 aspect ratio, HDR video + photo, Waterproof to 10m, Max Lens Mod compatible, 4K vertical video",
  },
  {
    id: "prod_camera_5",
    name: "Nikon Z8",
    category: "Cameras",
    price: 349995,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?w=800&q=80&auto=format&fit=crop",
    imageHint: "nikon z8 professional mirrorless camera",
    description: "The Z9 performance in a significantly smaller body. The Z8 packs a 45.7MP stacked CMOS sensor, 8.3K N-RAW video at up to 60fps, and a blackout-free 20fps mechanical shutter into a body that weighs 200g less than its big brother. The autofocus subject detection works in near darkness.",
    specifications: "45.7MP FX Stacked CMOS, 8.3K 60p N-RAW, 4K 120p, 20fps mechanical / 120fps electronic, 493-point AF with subject detection, -9EV focus sensitivity",
  },

  // ── Keyboards ────────────────────────────────────────────────────────────
  {
    id: "prod_keyboard_1",
    name: "Logitech MX Keys S",
    category: "Keyboards",
    price: 10995,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80&auto=format&fit=crop",
    imageHint: "logitech mx keys wireless keyboard",
    description: "The smartest keyboard for professionals who live in multiple apps. Smart Backlighting adapts to ambient light and turns off when you walk away. MX Keys S connects to three devices simultaneously and switches between them with a tap. The spherically-dished keys are shaped to your fingertips.",
    specifications: "Bluetooth + USB receiver, Connect 3 devices, Smart backlighting with ambient sensor, USB-C rechargeable 10 days per charge, Low-profile PerfectStroke keys, Numpad",
  },
  {
    id: "prod_keyboard_2",
    name: "Keychron Q1 Pro QMK/VIA",
    category: "Keyboards",
    price: 14500,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1595225386386-79c3543adbd9?w=800&q=80&auto=format&fit=crop",
    imageHint: "keychron mechanical keyboard rgb custom",
    description: "The most customisable mechanical keyboard you can buy without soldering. Full QMK/VIA support lets you remap every key via software. Gasket-mount construction reduces vibration for a softer, more satisfying typing feel. Available with Gateron G Pro switches in red, brown, or blue.",
    specifications: "Gasket mount, Hot-swap PCB, QMK/VIA firmware, Bluetooth 5.1 + USB-C wired, RGB per-key, South-facing PCB, Cherry-profile keycap compatibility, Aluminium body",
  },
  {
    id: "prod_keyboard_3",
    name: "Razer BlackWidow V4 Pro",
    category: "Keyboards",
    price: 19999,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=800&q=80&auto=format&fit=crop",
    imageHint: "razer gaming keyboard rgb mechanical",
    description: "Razer's flagship gaming keyboard for streamers and power users. The multi-function digital dial controls volume, zoom, and app-specific shortcuts on the fly. Six dedicated macro keys, Chroma RGB with 16.8 million colours, and Razer Yellow switches make it a complete command centre.",
    specifications: "Razer Yellow tactile switches, Multi-function digital dial, 6 macro keys, Chroma RGB 16.8M colours, Detachable wrist rest, USB-A passthrough, Razer Synapse 3",
  },
  {
    id: "prod_keyboard_4",
    name: "Apple Magic Keyboard with Touch ID",
    category: "Keyboards",
    price: 12900,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&q=80&auto=format&fit=crop",
    imageHint: "apple magic keyboard aluminium touch id",
    description: "The keyboard that feels right at home with any Mac. Scissor-switch keys with a comfortable 1mm travel and Touch ID let you log in with your fingerprint instantly. The anodised aluminium build is both premium and lightweight. USB-C rechargeable and a full charge lasts a month.",
    specifications: "Touch ID fingerprint reader, Scissor mechanism keys, 1mm key travel, Bluetooth + USB-C wired, Rechargeable 1 month per charge, Numpad available, Anodised aluminium",
  },

  // ── TVs ───────────────────────────────────────────────────────────────────
  {
    id: "prod_tv_1",
    name: "Samsung 65 inch S95D QD-OLED 4K TV",
    category: "TVs",
    price: 329990,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80&auto=format&fit=crop",
    imageHint: "samsung qd-oled 4k smart tv",
    description: "Samsung's best TV. The second-generation QD-OLED panel with a new Glare-Free coating makes it viewable even in bright living rooms. Quantum HDR OLED+ delivers 2000 nits of peak brightness, while the new 14-channel Neural Quantum Processor 4K upscales any content to near-native quality.",
    specifications: "65 inch 4K QD-OLED, 2000 nits peak, Glare-Free coating, 144Hz VRR, HDMI 2.1 4 ports, Dolby Atmos, Neural Quantum 4K processor, 0.1ms response, Tizen OS",
  },
  {
    id: "prod_tv_2",
    name: "LG 65 inch G4 OLED Evo 4K",
    category: "TVs",
    price: 359990,
    rating: 4.9,
    imageUrl: "https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=800&q=80&auto=format&fit=crop",
    imageHint: "lg oled evo 4k smart television",
    description: "LG's absolute finest. The G4 introduces Micro Lens Array technology that concentrates light more efficiently, pushing OLED brightness to unprecedented levels. The Alpha 11 AI processor provides 70% better performance than its predecessor for upscaling and audio processing.",
    specifications: "65 inch 4K OLED Evo with MLA+, Alpha 11 AI processor, 3000 nits peak, 144Hz HDMI 2.1 4 ports, Dolby Vision IQ, Dolby Atmos, webOS 24, Gallery design wall-flush",
  },
  {
    id: "prod_tv_3",
    name: "Sony 55 inch Bravia 7 Mini LED 4K",
    category: "TVs",
    price: 179990,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80&auto=format&fit=crop",
    imageHint: "sony bravia mini led 4k television",
    description: "Sony Mini LED technology at its finest, powered by the XR Cognitive Processor that analyses content the way a human brain perceives it. Acoustic Multi-Audio places sound at the exact position of what is happening on screen. Google TV integration gives you instant access to every streaming service.",
    specifications: "55 inch 4K Mini LED, XR Cognitive Processor, 1000 nits, 120Hz, HDMI 2.1, Dolby Vision + Atmos, Acoustic Multi-Audio, Google TV, PlayStation 5 optimised",
  },
  {
    id: "prod_tv_4",
    name: "TCL 65 inch C845 Mini LED QLED 4K",
    category: "TVs",
    price: 119990,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1548324215-9133768a2314?w=800&q=80&auto=format&fit=crop",
    imageHint: "tcl mini led qled 4k tv large screen",
    description: "The undisputed champion of affordable brilliance. TCL's C845 delivers Mini LED performance typically found at twice the price. With 1344 local dimming zones and up to 2000 nits of brightness, HDR content genuinely pops. The 144Hz panel with VRR support makes it a gamer's dream.",
    specifications: "65 inch 4K QLED Mini LED, 1344 local dimming zones, 2000 nits, 144Hz, VRR + ALLM, HDMI 2.1 2 ports, Dolby Vision IQ, Google TV, Onkyo 2.1ch speakers",
  },
  {
    id: "prod_tv_5",
    name: "Hisense 55 inch U8N Mini LED ULED",
    category: "TVs",
    price: 89990,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80&auto=format&fit=crop",
    imageHint: "hisense uled mini led television value",
    description: "Hisense best mid-range TV delivers premium performance without the premium price. ULED Mini LED technology with over 1000 local dimming zones ensures deep blacks and vibrant highlights. The 144Hz panel with Dolby Vision and built-in Google TV makes it a complete smart TV solution.",
    specifications: "55 inch 4K ULED Mini LED, 1000+ dimming zones, 1500 nits, 144Hz, HDMI 2.1 2 ports, Dolby Vision + Atmos, Google TV, AMD FreeSync Premium, 2.1ch built-in sound",
  },

  // ── Groceries ─────────────────────────────────────────────────────────────
  {
    id: "prod_grocery_1",
    name: "Organic Hass Avocados (Pack of 6)",
    category: "Groceries",
    price: 349,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&q=80&auto=format&fit=crop",
    imageHint: "fresh organic avocados halved green",
    description: "Creamy, perfectly ripened Hass avocados sourced from certified organic farms. Rich in heart-healthy monounsaturated fats, potassium, and vitamins K, C, and E. Perfect for guacamole, avocado toast, salads, or smoothies. Ready to eat within 1 to 2 days of delivery.",
    specifications: "Pack of 6, Certified Organic, Hass variety, Country of origin Mexico, Net weight approx 800g, Ready to eat in 1 to 2 days, No pesticides, No artificial ripening",
  },
  {
    id: "prod_grocery_2",
    name: "Tata Himalayan Pink Rock Salt (1kg)",
    category: "Groceries",
    price: 199,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=800&q=80&auto=format&fit=crop",
    imageHint: "himalayan pink salt crystals coarse",
    description: "Mined from the ancient Khewra Salt Mine in Pakistan, Himalayan pink salt is one of the purest salts on Earth. It contains 84 trace minerals including iron, calcium, and magnesium. A healthier, flavourful alternative to processed table salt.",
    specifications: "1kg coarse grain, 84 trace minerals, No additives or anti-caking agents, Sourced from Khewra Salt Mine Pakistan, Suitable for cooking, baths, and salt lamps",
  },
  {
    id: "prod_grocery_3",
    name: "Figaro Extra Virgin Olive Oil (1L)",
    category: "Groceries",
    price: 799,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80&auto=format&fit=crop",
    imageHint: "extra virgin olive oil bottle dark glass",
    description: "Cold-pressed from handpicked olives within 24 hours of harvest, Figaro EVOO retains maximum polyphenols and antioxidants. Its robust, fruity flavour with a peppery finish is characteristic of quality Mediterranean olive oil. Ideal for drizzling, dipping, and salad dressings.",
    specifications: "1 litre, Cold-first pressed, Acidity under 0.8%, Polyphenol rich, Product of Spain, Dark glass bottle UV protection, Smoke point 190 degrees C, Best before 24 months",
  },
  {
    id: "prod_grocery_4",
    name: "Natures Truth Almond Flour (500g)",
    category: "Groceries",
    price: 449,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
    imageHint: "almond flour baking ingredient gluten free",
    description: "Finely blanched almond flour made from California-grown almonds. The extra-fine grind ensures smooth textures in macarons, cakes, and muffins. Naturally gluten-free, grain-free, and low-carb, perfect for keto and paleo diets. Packed with protein, healthy fats, and vitamin E.",
    specifications: "500g, Extra-fine blanched almond flour, Gluten-free certified, Non-GMO, 6g protein per 28g serving, 14g fat per serving, Keto and Paleo friendly",
  },
  {
    id: "prod_grocery_5",
    name: "Organic Tattva Tri-Colour Quinoa (500g)",
    category: "Groceries",
    price: 299,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80&auto=format&fit=crop",
    imageHint: "quinoa grain seeds bowl organic healthy",
    description: "A blend of white, red, and black quinoa for superior nutrition and visual appeal. Quinoa is one of the few plant foods that is a complete protein, containing all 9 essential amino acids. Pre-washed to remove natural bitterness, it cooks in just 15 minutes. Certified organic and non-GMO.",
    specifications: "500g tri-colour blend white red black, USDA Organic certified, Complete protein 8g per serving, Pre-washed, Cooks in 15 minutes, Gluten-free, Non-GMO verified",
  },

  // ── Ethnic Wear ──────────────────────────────────────────────────────────
  {
    id: "prod_ethnic_1",
    name: "Banarasi Pure Silk Saree with Zari Work",
    category: "Ethnic Wear",
    price: 12999,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80&auto=format&fit=crop",
    imageHint: "banarasi silk saree zari gold border indian",
    description: "A timeless masterpiece woven by artisans in Varanasi. This Banarasi silk saree features intricate gold zari work borders and a richly embellished pallu with traditional motifs. The pure silk fabric drapes gracefully and catches the light beautifully. Includes an unstitched blouse piece.",
    specifications: "Pure silk, Zari work border + pallu, Includes unstitched blouse piece 0.8m, Length 5.5m, Dry-clean only, GOTS certified silk, Handwoven by Varanasi artisans",
  },
  {
    id: "prod_ethnic_2",
    name: "Manyavar Mens Embroidered Kurta Set",
    category: "Ethnic Wear",
    price: 4999,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1598369072286-12c57e47e21d?w=800&q=80&auto=format&fit=crop",
    imageHint: "men kurta set indian ethnic wear festive",
    description: "A festive-ready kurta set from Manyavar, India's most trusted ethnic menswear brand. The ivory cotton kurta features subtle thread embroidery at the collar and cuffs. Paired with matching churidar bottoms, this ensemble is perfect for weddings, pujas, and festive celebrations.",
    specifications: "Cotton blend, Thread embroidery, Mandarin collar, Side slits, Includes kurta + churidar set, Machine washable, Available in S to 3XL, Festive collection",
  },
  {
    id: "prod_ethnic_3",
    name: "Anarkali Floor-Length Gown with Dupatta",
    category: "Ethnic Wear",
    price: 3499,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80&auto=format&fit=crop",
    imageHint: "anarkali gown floor length ethnic wear indian woman",
    description: "An elegant floor-length Anarkali gown crafted from premium georgette fabric. The flared silhouette is timeless and universally flattering. Delicate thread and sequin embroidery adorns the bodice and hemline. Includes a coordinating chiffon dupatta with border embroidery.",
    specifications: "Georgette fabric, Thread + sequin embroidery, Floor-length, A-line flare, Includes dupatta, Semi-stitched adjustable, Inner lining included, Dry-clean recommended",
  },
  {
    id: "prod_ethnic_4",
    name: "Lucknowi Chikankari Straight Kurta",
    category: "Ethnic Wear",
    price: 2199,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1609912139753-7d9e05a0d42e?w=800&q=80&auto=format&fit=crop",
    imageHint: "chikankari white cotton kurta hand embroidered lucknow",
    description: "Authentic Lucknowi Chikankari hand-embroidery on soft cotton fabric. Each piece is embroidered by skilled artisans from Lucknow using traditional shadow-work techniques. The breathable cotton makes it perfect for the Indian summer while the embroidery keeps it festive.",
    specifications: "Cotton fabric, Hand-embroidered Chikankari, Mandarin collar, Full sleeves, Length 44 inches, Machine wash cold, GI Tag authentic Lucknow Chikankari",
  },
  {
    id: "prod_ethnic_5",
    name: "Brocade Nehru Jacket Wedding Special",
    category: "Ethnic Wear",
    price: 3299,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1623682708098-af5e9bd9e95b?w=800&q=80&auto=format&fit=crop",
    imageHint: "nehru jacket brocade ethnic men indian wedding",
    description: "Elevate any ethnic look with this royal brocade Nehru jacket. The rich jacquard weave creates a textured, jewel-toned pattern that catches the light. Completely sleeveless with a mandarin collar and concealed button placket, it can be layered over a kurta or shirt for festive occasions.",
    specifications: "Brocade jacquard fabric, Fully lined, Mandarin collar, Concealed buttons, Sleeveless, Dry-clean only, Available in S to 4XL, Wedding + festive occasion",
  },

  // ── T-Shirts ──────────────────────────────────────────────────────────────
  {
    id: "prod_tshirt_1",
    name: "Supima Cotton Crew Neck T-Shirt",
    category: "T-shirts",
    price: 1499,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&q=80&auto=format&fit=crop",
    imageHint: "white crew neck cotton t shirt folded flat lay",
    description: "Made from 100% Supima cotton — a superior American-grown cotton that is longer, softer, and more durable than regular cotton. The yarn-dyed fabric resists fading wash after wash. A perfect-weight staple at 180 GSM that is thick enough to be opaque but light enough for year-round comfort.",
    specifications: "100% Supima Cotton, 180 GSM, Regular fit, Tagless neck, Reinforced shoulder seams, Pre-shrunk, Machine wash 30 degrees C, Available in 12 colours, S to 3XL",
  },
  {
    id: "prod_tshirt_2",
    name: "Bewakoof Graphic Print Oversized Tee",
    category: "T-shirts",
    price: 649,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80&auto=format&fit=crop",
    imageHint: "oversized graphic t shirt streetwear printed",
    description: "India's favourite destination for expressive graphic tees. This oversized drop-shoulder tee features a bold, conversation-starting print on heavyweight 240 GSM cotton. The boxy silhouette and dropped shoulders create the quintessential streetwear look without trying too hard.",
    specifications: "100% Cotton, 240 GSM, Oversized drop-shoulder fit, Screen-printed graphic, Ribbed collar, Machine wash, Available in 20+ designs, XS to 4XL",
  },
  {
    id: "prod_tshirt_3",
    name: "H&M Striped Pocket T-Shirt",
    category: "T-shirts",
    price: 999,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&q=80&auto=format&fit=crop",
    imageHint: "breton stripe t shirt cotton pocket",
    description: "A classic striped T-shirt done right. Yarn-dyed Breton stripes ensure the colours never fade, and the small chest pocket adds a distinctive detail. Made from 100% organic cotton, it sits just right — not too slim, not too boxy — with a crew neck and short sleeves.",
    specifications: "100% Organic Cotton GOTS certified, Yarn-dyed Breton stripes, Chest patch pocket, Regular fit, Crew neck, Machine wash 40 degrees C",
  },
  {
    id: "prod_tshirt_4",
    name: "Levis Slim Fit V-Neck T-Shirt",
    category: "T-shirts",
    price: 1299,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80&auto=format&fit=crop",
    imageHint: "levis v-neck slim fit cotton tee",
    description: "Levi's brings its iconic quality to a slim-fit V-neck. The fabric is a cotton-modal blend that is extraordinarily soft with a subtle lustre. The V-neck is flattering without being too deep, and the slim cut is tailored without being restrictive. A step up from your average tee.",
    specifications: "60% Cotton, 40% Modal, Slim fit, V-neckline, Short sleeves, Tagless neck label, Machine wash cold, Pre-shrunk, Available in 8 colours",
  },
  {
    id: "prod_tshirt_5",
    name: "Nike Dri-FIT Training T-Shirt",
    category: "T-shirts",
    price: 2495,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80&auto=format&fit=crop",
    imageHint: "nike dri-fit sports training t shirt",
    description: "Train harder with Nike Dri-FIT technology that wicks sweat away from your skin and dries quickly to keep you comfortable. The lightweight fabric moves with your body during even the most intense workouts, while the loose fit allows for unrestricted movement.",
    specifications: "100% Polyester Dri-FIT, Moisture-wicking, Quick-dry, Standard fit, Crew neck, Embroidered Nike Swoosh, Machine wash, UPF 40+ sun protection",
  },

  // ── Hoodies ───────────────────────────────────────────────────────────────
  {
    id: "prod_hoodie_1",
    name: "Puma Essentials Fleece Pullover Hoodie",
    category: "Hoodies",
    price: 2299,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80&auto=format&fit=crop",
    imageHint: "puma fleece pullover hoodie sweatshirt",
    description: "Puma's classic essentials hoodie that never goes out of style. Made from a warm cotton-polyester fleece blend with a brushed interior for supreme softness. The kangaroo pocket doubles as a hand warmer, and the drawstring hood provides cosy coverage on chilly days.",
    specifications: "80% Cotton, 20% Polyester fleece, Brushed interior, Ribbed cuffs + hem, Kangaroo pocket, Drawstring hood, Machine wash, Regular fit, S to 4XL",
  },
  {
    id: "prod_hoodie_2",
    name: "Nike Tech Fleece Full-Zip Hoodie",
    category: "Hoodies",
    price: 7995,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1620799139834-6b8f844fbe61?w=800&q=80&auto=format&fit=crop",
    imageHint: "nike tech fleece full zip hoodie modern",
    description: "Nike Tech Fleece is the gold standard of athletic hoodies. The innovative dual-layer fabric traps warmth without adding bulk, making it dramatically lighter than traditional fleece. Articulated patterning ensures the sleeves always stay in the right position during movement.",
    specifications: "Nike Tech Fleece dual-layer, Articulated patterning, Full zip, Raglan sleeves, Zippered side pockets, Slim fit, Machine wash, 450g",
  },
  {
    id: "prod_hoodie_3",
    name: "The North Face Drew Peak Pullover Hoodie",
    category: "Hoodies",
    price: 6495,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=800&q=80&auto=format&fit=crop",
    imageHint: "north face heavyweight cotton hoodie logo",
    description: "The iconic outdoor hoodie with The North Face signature box logo embroidered on the chest. Made from heavyweight 300 GSM cotton fleece, this hoodie is warm enough for mountain trails and stylish enough for city streets. A lifetime staple that only gets better with age.",
    specifications: "300 GSM heavyweight cotton fleece, Box logo embroidery, Double-lined drawstring hood, Kangaroo pocket, Ribbed cuffs + hem, Machine wash, Regular fit",
  },
  {
    id: "prod_hoodie_4",
    name: "Adidas Trefoil Graphic Hoodie",
    category: "Hoodies",
    price: 4499,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=800&q=80&auto=format&fit=crop",
    imageHint: "adidas trefoil logo hoodie streetwear",
    description: "A streetwear icon with the legendary Trefoil logo that has been turning heads since 1972. The relaxed fit and soft French terry fabric make it the ideal casual layer, while the bold graphic is a statement in itself. Available in a full spectrum of seasonal colourways.",
    specifications: "70% Cotton, 30% Polyester French Terry, Relaxed fit, Screen-printed Trefoil logo, Kangaroo pocket, Drawstring hood, Machine wash",
  },
  {
    id: "prod_hoodie_5",
    name: "Mango Colourblock Oversized Hoodie",
    category: "Hoodies",
    price: 3299,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80&auto=format&fit=crop",
    imageHint: "oversized colour block hoodie fashion streetwear",
    description: "A fashion-forward hoodie that makes a statement through colour. Mango's panelled colour-block design pairs bold complementary tones in a boxy oversized silhouette. Soft brushed interior keeps you warm from autumn through early spring.",
    specifications: "80% Cotton, 20% Polyester, Brushed interior, Oversized boxy fit, Colour-block panel design, Ribbed cuffs + hem, Kangaroo pocket, Machine wash",
  },

  // ── Jewellery ─────────────────────────────────────────────────────────────
  {
    id: "prod_jewellery_1",
    name: "925 Sterling Silver Hoop Earrings 40mm",
    category: "Jewellery",
    price: 1299,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80&auto=format&fit=crop",
    imageHint: "sterling silver hoop earrings polished",
    description: "Classic silver hoops that never go out of style. Crafted from solid 925 sterling silver with a high-polish finish that catches the light beautifully. The 40mm diameter is the sweet spot — large enough to make a statement, small enough to wear to the office. Hypoallergenic for sensitive ears.",
    specifications: "925 Sterling Silver hallmarked, 40mm diameter, 2.5mm tube thickness, Push-lock closure, Hypoallergenic, Rhodium plated tarnish resistant, Comes in gift box",
  },
  {
    id: "prod_jewellery_2",
    name: "18K Gold-Plated Layered Necklace Set",
    category: "Jewellery",
    price: 2199,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80&auto=format&fit=crop",
    imageHint: "gold layered necklace pendant chain set jewelry",
    description: "Three necklaces, infinite combinations. This layering set includes a 16-inch delicate chain, an 18-inch pendant necklace with a cubic zirconia teardrop, and a 20-inch longer statement piece. Wear all three together for a curated layered look or separately for everyday elegance.",
    specifications: "18K gold plating over 925 silver, Set of 3 necklaces 16 inch 18 inch 20 inch, Cubic zirconia pendant, Lobster-claw clasp, Tarnish-resistant, Hypoallergenic",
  },
  {
    id: "prod_jewellery_3",
    name: "Oxidised Silver Chandbali Earrings",
    category: "Jewellery",
    price: 799,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1576022162028-c351c28f2c29?w=800&q=80&auto=format&fit=crop",
    imageHint: "indian oxidised silver chandbali jhumka earrings",
    description: "Traditional Indian Chandbali earrings with an antique silver finish. The oxidised treatment gives them an heirloom appearance, and intricate filigree work showcases centuries of Indian jewellery craftsmanship. Lightweight German silver construction ensures all-day comfort despite their dramatic appearance.",
    specifications: "German Silver, Oxidised antique finish, Filigree work, Hook fitting, 8cm drop length, 45g per pair, Lightweight for comfort, Traditional Indian craftsmanship",
  },
  {
    id: "prod_jewellery_4",
    name: "Natural Freshwater Pearl Bracelet",
    category: "Jewellery",
    price: 3499,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800&q=80&auto=format&fit=crop",
    imageHint: "freshwater pearl bracelet elegant silver clasp",
    description: "Genuine freshwater pearls hand-knotted on silk thread with a sterling silver clasp. Each pearl is carefully selected for its lustre and near-round shape. The slight natural variation in colour and size makes each bracelet uniquely beautiful and unmistakably real.",
    specifications: "Genuine freshwater pearls, 7 to 8mm diameter, Hand-knotted on silk thread, 925 Sterling Silver clasp, Single strand, Length 18cm + 2cm extender, Certificate of authenticity",
  },
  {
    id: "prod_jewellery_5",
    name: "Minimalist Stainless Steel Signet Ring",
    category: "Jewellery",
    price: 999,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80&auto=format&fit=crop",
    imageHint: "minimalist signet ring stainless steel brushed unisex",
    description: "A modern take on a centuries-old style. This flat-faced signet ring in brushed 316L stainless steel is virtually scratch-proof and will never tarnish or discolour. The understated design works equally well for men and women and pairs with any outfit from casual denim to a formal suit.",
    specifications: "316L Stainless Steel surgical grade, Brushed finish, 8mm face width, 2mm band thickness, Hypoallergenic, Tarnish-proof, Sizes 6 to 13 available, Unisex design",
  },

  // ── Decorative Items ──────────────────────────────────────────────────────
  {
    id: "prod_decor_1",
    name: "Handwoven Cotton Macrame Wall Hanging",
    category: "Decorative Items",
    price: 1499,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
    imageHint: "macrame wall hanging boho handmade cotton rope",
    description: "A stunning bohemian wall hanging hand-knotted by artisans using 100% natural cotton rope. The intricate knotwork creates beautiful texture and movement. Mounted on a sustainable mango wood dowel with leather loops for hanging. Adds instant warmth and artisanal character to any room.",
    specifications: "100% natural cotton rope, Mango wood dowel, Leather hanging loop, Size 60cm W x 90cm L, Handmade, Natural undyed cotton off-white, Each piece is unique",
  },
  {
    id: "prod_decor_2",
    name: "Ceramic Matte Planter Set of 3",
    category: "Decorative Items",
    price: 1299,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80&auto=format&fit=crop",
    imageHint: "ceramic matte planters set modern indoor pots",
    description: "A curated set of three matte-finish ceramic planters in complementary neutral tones in stone, sage, and terracotta. Available in three graduated sizes, they create an effortlessly styled vignette on shelves and windowsills. Each pot includes a drainage hole and a removable plug.",
    specifications: "Set of 3 Small 9cm Medium 12cm Large 15cm diameter, Ceramic with matte glaze, Drainage hole + removable plug, Colours Stone Sage Terracotta, Dishwasher safe",
  },
  {
    id: "prod_decor_3",
    name: "Soy Wax Scented Candle Sandalwood and Amber",
    category: "Decorative Items",
    price: 899,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=800&q=80&auto=format&fit=crop",
    imageHint: "soy wax candle glass jar wooden wick sandalwood",
    description: "A luxury soy wax candle with a warm, grounding fragrance of Indian sandalwood, amber resin, and a hint of vanilla. Soy wax burns cleaner and longer than paraffin, with zero black soot. The wooden wick creates a gentle crackling sound reminiscent of a fireplace. 50-hour burn time.",
    specifications: "200g soy wax, Wooden wick, Fragrance Sandalwood + Amber + Vanilla, 50-hour burn time, Glass jar reusable, Lead-free, Vegan, Cruelty-free, Hand-poured in India",
  },
  {
    id: "prod_decor_4",
    name: "Solid Mango Wood Floating Wall Shelves Set of 2",
    category: "Decorative Items",
    price: 2499,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80&auto=format&fit=crop",
    imageHint: "mango wood floating wall shelves rustic natural",
    description: "Handcrafted from solid reclaimed mango wood, each shelf has a unique natural grain pattern that makes it one-of-a-kind. The invisible bracket system creates a true floating effect. Each shelf holds up to 15kg, making it suitable for books, plants, and decorative objects.",
    specifications: "Set of 2, Solid mango wood, Invisible floating bracket, Dimensions 60cm L x 20cm D x 3.5cm H, Load 15kg each, Includes wall plugs + screws, Natural wax finish",
  },
  {
    id: "prod_decor_5",
    name: "Gallery-Wrapped Abstract Canvas Art Print",
    category: "Decorative Items",
    price: 1999,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&q=80&auto=format&fit=crop",
    imageHint: "abstract canvas art print gallery wall modern",
    description: "A bold abstract art print that brings gallery-quality aesthetics into your home. Printed with archival-grade inks on 350 GSM canvas and stretched over a 3.8cm deep wooden frame. Arrives ready to hang with pre-installed D-ring hardware. Works with both modern and eclectic decor.",
    specifications: "60cm x 80cm, 350 GSM archival canvas, 3.8cm deep gallery frame, Archival giclee print, UV-resistant inks 100-year fade resistance, Pre-installed hanging hardware",
  },

  // ── Shirts ────────────────────────────────────────────────────────────────
  {
    id: "prod_shirt_1",
    name: "Van Heusen Linen Regular Fit Shirt",
    category: "Shirts",
    price: 2299,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80&auto=format&fit=crop",
    imageHint: "linen formal dress shirt men white regular fit",
    description: "The perfect warm-weather office shirt. Van Heusen's 100% linen fabric is breathable, moisture-absorbent, and naturally textured. It looks effortlessly polished while keeping you cool in Indian summers. The classic regular fit with a cutaway collar and mother-of-pearl buttons dresses it up without effort.",
    specifications: "100% Premium Linen, Regular fit, Full sleeves, Cutaway collar, Mother-of-pearl buttons, Breast pocket, Machine wash cold, Anti-static",
  },
  {
    id: "prod_shirt_2",
    name: "Peter England Oxford Cloth Button-Down",
    category: "Shirts",
    price: 1799,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1563630423918-b58f07336ac9?w=800&q=80&auto=format&fit=crop",
    imageHint: "oxford cloth button down shirt men smart casual",
    description: "The OCBD is one of the most versatile shirts ever designed — it works equally well with chinos and loafers or jeans and sneakers. Peter England's version uses a classic Oxford cotton weave that is slightly textured and gets softer with every wash. A wardrobe essential.",
    specifications: "100% Oxford Cotton, Regular fit, Button-down collar, Long sleeves, Chest pocket, Machine wash 40 degrees C, Available in 8 colours including white sky blue pink",
  },
  {
    id: "prod_shirt_3",
    name: "Levis Denim Workshirt Regular Fit",
    category: "Shirts",
    price: 3499,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&q=80&auto=format&fit=crop",
    imageHint: "denim chambray workshirt levis classic western",
    description: "A modern take on an American workwear classic. Levi's denim workshirt is cut from midweight indigo chambray that softens beautifully with age and washing. Two chest pockets with snap closures, reinforced stitching at stress points, and a classic Western yoke on the back.",
    specifications: "100% Cotton chambray midweight, Regular fit, Snap button closures, Dual chest pockets, Western yoke, Reinforced stitching, Machine wash inside out 30 degrees C",
  },
  {
    id: "prod_shirt_4",
    name: "Allen Solly Slim Fit Check Flannel Shirt",
    category: "Shirts",
    price: 2099,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80&auto=format&fit=crop",
    imageHint: "flannel plaid check shirt slim fit winter casual",
    description: "Allen Solly's best-loved casual shirt in a classic tartan check. Made from brushed cotton flannel that is especially soft and warm, this shirt is the ideal companion for winter and monsoon. The slim fit keeps it looking sharp whether you tuck it in or leave it untucked over jeans.",
    specifications: "100% Brushed Cotton Flannel, Slim fit, Full sleeves, Spread collar, Single breast pocket, Machine wash 30 degrees C, 10 tartan colour combinations",
  },
  {
    id: "prod_shirt_5",
    name: "H&M Relaxed Camp Collar Linen Shirt",
    category: "Shirts",
    price: 1699,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1618517351616-38fb9952h=800&q=80&auto=format&fit=crop",
    imageHint: "camp collar linen summer shirt relaxed fit holiday",
    description: "The shirt that signals summer. H&M's camp collar shirt in a lightweight linen-viscose blend drapes and breathes beautifully. The open notch collar sits flat without a tie, making it perfect for beach holidays, brunch, and warm evenings out. Straight hemline allows for casual untucked wearing.",
    specifications: "55% Linen, 45% Viscose, Relaxed fit, Camp notch collar, Short sleeves, Straight hem, Side vents, Chest pocket, Machine wash 30 degrees C",
  },

  // ── Dresses ───────────────────────────────────────────────────────────────
  {
    id: "prod_dress_1",
    name: "Wrap Maxi Dress with Floral Print",
    category: "Dresses",
    price: 3299,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=80&auto=format&fit=crop",
    imageHint: "floral wrap maxi dress flowing summer women",
    description: "The dress you will wear on repeat all summer. A V-neckline wraps into a self-tie waist that cinches at the perfect point, then falls into a flowing maxi skirt with a flirty ruffle hem. The lightweight woven fabric in a vivid botanical print is romantic without trying too hard.",
    specifications: "100% Viscose Georgette, Adjustable tie waist, V-neckline, Maxi length, Ruffle hem, Short flutter sleeves, Fully lined skirt, Machine wash cold",
  },
  {
    id: "prod_dress_2",
    name: "Ribbed Knit Bodycon Midi Dress",
    category: "Dresses",
    price: 2499,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80&auto=format&fit=crop",
    imageHint: "ribbed knit bodycon midi dress form fitting women",
    description: "A wardrobe essential for its versatility. This mid-weight ribbed knit in a figure-flattering midi length goes from office to evening with just a shoe change. The stretchy fabric moulds to the body without feeling tight, and the square neckline is universally flattering.",
    specifications: "92% Viscose, 8% Elastane ribbed knit, Midi length ankle-grazing, Square neckline, Sleeveless, Form-fitting, Hand wash or machine wash gentle, S to 2XL",
  },
  {
    id: "prod_dress_3",
    name: "Tiered Smocked Cotton Sundress",
    category: "Dresses",
    price: 1999,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1550639525-c97d455acf70?w=800&q=80&auto=format&fit=crop",
    imageHint: "smocked cotton sundress tiered skirt summer women",
    description: "The ideal holiday dress. Made from 100% cotton poplin with a smocked elastic bodice that stretches to fit and then returns to shape. Three tiered skirt panels create movement with every step. The square neckline and adjustable straps make it a summer-capsule essential that travels well.",
    specifications: "100% Cotton Poplin, Smocked elastic bodice, 3-tier skirt, Square neckline, Adjustable shoulder straps, Mini to midi length depending on height, Machine wash",
  },
  {
    id: "prod_dress_4",
    name: "Zara Satin Slip Midi Dress",
    category: "Dresses",
    price: 4490,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80&auto=format&fit=crop",
    imageHint: "satin slip midi dress elegant evening women",
    description: "Effortlessly chic. Zara's bias-cut satin slip dress features a delicate lace trim at the neckline and hem that elevates it beyond casual into true evening elegance. The satin flows beautifully and catches the light. Style with trainers for a cool daytime look or heels for an evening out.",
    specifications: "100% Polyester Satin weave, Bias cut, Lace trim neckline + hem, Adjustable spaghetti straps, Midi length, V-back, Dry clean recommended",
  },
  {
    id: "prod_dress_5",
    name: "Shirt Dress with Detachable Belt",
    category: "Dresses",
    price: 2799,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80&auto=format&fit=crop",
    imageHint: "shirt dress belted cotton women smart casual",
    description: "A dress that works as hard as you do. The crisp cotton-poplin shirt dress transitions seamlessly from a weekday work outfit when belted with pointed-toe flats, to a weekend casual look unbelted with white sneakers. Button-front closure and a spread collar give it structured polish.",
    specifications: "65% Cotton, 35% Polyester, Button-front, Spread collar, Long sleeves with roll-up tab, Detachable D-ring belt, Knee length, 2 side patch pockets, Machine wash",
  },

  // ── Bottoms ───────────────────────────────────────────────────────────────
  {
    id: "prod_bottom_1",
    name: "Levis 501 Original Straight Jeans",
    category: "Bottoms",
    price: 4199,
    rating: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80&auto=format&fit=crop",
    imageHint: "levis 501 original straight jeans denim blue",
    description: "The original blue jean since 1873 — and still the standard by which all others are measured. The 501's iconic straight leg and high rise have never looked more current. Made from rigid 12.5oz denim that molds to your body with every wear, creating a fit that is entirely your own.",
    specifications: "99% Cotton, 1% Elastane, 12.5oz rigid denim, Original straight fit, High rise, Button fly, 5-pocket styling, Machine wash cold inside out, Shrink-to-fit",
  },
  {
    id: "prod_bottom_2",
    name: "H&M Wide-Leg Linen-Blend Trousers",
    category: "Bottoms",
    price: 2499,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=800&q=80&auto=format&fit=crop",
    imageHint: "wide leg linen trousers women summer tailored",
    description: "The most effortless summer trousers you will own. A linen-viscose blend keeps them breathable and naturally wrinkled in all the right ways. A front pleat adds a tailored touch while the elasticated back waistband keeps them comfortable all day. Pairs beautifully with fitted tops and mules.",
    specifications: "55% Linen, 45% Viscose, Wide leg, Pleat-front, Elasticated back waistband, Side pockets, High rise, Machine wash 30 degrees C, Naturally wrinkled texture",
  },
  {
    id: "prod_bottom_3",
    name: "Decathlon Mens Cargo Jogger Pants",
    category: "Bottoms",
    price: 1499,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&q=80&auto=format&fit=crop",
    imageHint: "cargo jogger pants men pockets outdoor trekking",
    description: "Maximum practicality meets casual style. Decathlon's cargo joggers feature 6 spacious pockets including two side cargo pockets with snap closures. The stretch twill fabric moves with you and the drawstring waistband with elastic cuffs locks in warmth. Perfect for travel, trekking, and everyday wear.",
    specifications: "97% Cotton, 3% Elastane stretch twill, 6 pockets including 2 cargo pockets, Drawstring waistband, Elastic cuffs, Regular fit, Machine wash, Water-repellent finish",
  },
  {
    id: "prod_bottom_4",
    name: "Mango A-Line Mini Denim Skirt",
    category: "Bottoms",
    price: 2199,
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4b8e27?w=800&q=80&auto=format&fit=crop",
    imageHint: "a-line mini denim skirt women button front",
    description: "The mini skirt is back and better than ever. Mango's A-line version in a medium-wash rigid denim sits at the natural waist and flares gently for a flattering shape. A button-front closure and slight fading give it authentic vintage denim character. Style with almost anything for instant cool.",
    specifications: "100% Cotton, 5-button front closure, Mid-rise, A-line silhouette, Mini length, Side pockets, Faded wash, Machine wash inside out cold",
  },
  {
    id: "prod_bottom_5",
    name: "Jockey Womens High-Rise Performance Leggings",
    category: "Bottoms",
    price: 1699,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80&auto=format&fit=crop",
    imageHint: "women high waist yoga leggings athletic performance",
    description: "Leggings that work as hard as you do. Jockey high-rise performance leggings use moisture-wicking, quick-dry fabric with 4-way stretch for total freedom of movement. The wide high-rise waistband stays put during even the most intense yoga sessions. A hidden phone pocket is tucked into the waistband.",
    specifications: "75% Nylon, 25% Spandex, 4-way stretch, Moisture-wicking, High-rise waistband 8cm, Hidden waistband phone pocket, Inseam 26 inches, UPF 50+, Machine wash",
  },

  // ── Tops ──────────────────────────────────────────────────────────────────
  {
    id: "prod_top_1",
    name: "Forever 21 Satin Cami Top",
    category: "Tops",
    price: 1299,
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80&auto=format&fit=crop",
    imageHint: "satin cami top sleeveless women strappy",
    description: "The satin cami that goes with everything. A versatile V-neckline and adjustable spaghetti straps make it endlessly adaptable — wear it solo for evenings, under a blazer for work, or layered under a cardigan for casual weekends. Available in 15 colours from neutrals to jewel tones.",
    specifications: "100% Polyester satin weave, V-neckline, Adjustable spaghetti straps, Cropped length, Side seam construction, Machine wash gentle cold, XS to XXL",
  },
  {
    id: "prod_top_2",
    name: "Chiffon Lace-Trim Blouse",
    category: "Tops",
    price: 1799,
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80&auto=format&fit=crop",
    imageHint: "chiffon lace blouse feminine puff sleeves women",
    description: "Feminine and romantic, this sheer chiffon blouse features intricate guipure lace insets at the neckline and sleeves. Long blouson sleeves with elasticated cuffs create a dramatic puff that balances beautifully with slim-fit bottoms. Pairs perfectly with high-waisted trousers or a pencil skirt.",
    specifications: "100% Polyester Chiffon with Guipure Lace insets, Blouson silhouette, Long puff sleeves with elasticated cuffs, V-neckline with button front, Hand wash cold",
  },
  {
    id: "prod_top_3",
    name: "Square Neck Ribbed Bodysuit",
    category: "Tops",
    price: 1499,
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&q=80&auto=format&fit=crop",
    imageHint: "square neck ribbed bodysuit women form fitting",
    description: "The bodysuit that completes any high-waisted look by eliminating any chance of untucking. A flattering square neckline is the season's most versatile choice, and the ribbed stretch fabric adapts perfectly to your body. Snap closures at the gusset make fitting easy and keep everything in place.",
    specifications: "92% Rayon, 8% Spandex ribbed, Square neckline, Sleeveless, Snap gusset closure, Thong-cut back, Form-fitting, Machine wash cold, Available in 10 colours",
  },
  {
    id: "prod_top_4",
    name: "Chunky Cable Knit Merino Sweater",
    category: "Tops",
    price: 3499,
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80&auto=format&fit=crop",
    imageHint: "chunky cable knit merino wool sweater cozy warm",
    description: "Sink into the warmth of a 100% pure merino wool sweater. The bold cable-knit pattern creates a raised 3D texture that is both visually striking and incredibly insulating. The relaxed fit and mock-neck collar keep you cosy without looking bulky. A winter wardrobe investment that will last years.",
    specifications: "100% Extra-Fine Merino Wool, Chunky cable-knit, Relaxed fit, Mock neck, Ribbed cuffs + hem, Hand wash or dry clean, 500 GSM, Available in cream navy forest green",
  },
];
